### ISSUE TITLE
VectorPython suggestions

### ISSUE THREAD

**Issue by johanez** [GeoScripting-WUR/PythonWeek#1]
python vector for next year:
- tell students to use jupyter notebook (or editor + console, or an IDE, not qgis)
- get rid of mapnik
- add geopandas and or Fiona/shaply examples, see e.g. https://github.com/kjordahl/SciPy-Tutorial-2015

**Comment by Davidswinkels** [comment]
This year the course was updated to use Jupyter Notebook instead of QGIS' python console, mapnik was not used and geopandas/fiona/shapely could be a nice addition

**Comment by Davidswinkels** [comment]
For this year GeoPandas, Shapely and Fiona were added for vector Python in new repository
