### ISSUE TITLE
Raster: Make use of new GDAL bindings for gdalwarp

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/PythonWeek#11]
In the raster tutorial, `gdalwarp` is run on the command line using the `!` operator in Jupyter. Instead, the new GDAL bindings should be used. Example by Sytze:
```python
ndvi_ll = gdal.Warp("data/ndvi_ll.tif", outDataSet, options=gdal.WarpOptions(dstSRS="EPSG:4326"))
```

**Comment by Davidswinkels** [comment]
@GreatEmerald Can this issue be transferred to the PythonRaster repository? (I don't have admin rights to do so). The PythonWeek repository will be deprecated, because PythonWeek content has been split to individual repositories.

**Comment by GreatEmerald** [comment]
I can't transfer it either (transferring is a beta function), but I'll just close this and open a new one there.
