### ISSUE TITLE
improvements geo-scripting and python

### ISSUE THREAD

**Issue by janverbesselt** [GeoScripting-WUR/PythonWeek#2]
- use a stable and simple IDE (e.g. spyder apt-get install spyder)
- make sure jupyter is updated to the latest version
- the raster python excercise: make the data set smaller using a shape file or extent (within the excercise).

**Comment by berald** [comment]
python(x,y) could be an alternative, also available for windows.
https://python-xy.github.io/

**Comment by Davidswinkels** [comment]
Spyder is now used as a stable simple IDE. Jupyter was updated in the Ubuntu 16.04 template to latest version and raster Python exercise now uses small raster datasets.
