### ISSUE TITLE
ipython notebook explanation needs to be improved

### ISSUE THREAD

**Issue by janverbesselt** [GeoScripting-WUR/PythonWeek#6]
- double check the description of Ipythonnotebook creation as it is not clear for the student how and what to submit

**Comment by Davidswinkels** [comment]
IPython notebooks were renamed to Jupyter Notebooks, since IPython Notebooks also allowed documentation of programming languages Julia and R besides Python. So they renamed it to Jupyter (JUlia, PYThon, and R). I'm working on a better description how to use Jupyter Notebooks.
