### ISSUE TITLE
Improve description of Python commands

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/PythonWeek#8]
Some students pointed out that compared to the R lessons, the Python ones largely come off as blocks of code to run without much explanation in between the lines, which makes it hard to understand what each line does exactly. The issue gets worse considering that it's more difficult to investigate objects in Python compared to R (lack of an `str()`-style function).

**Comment by Davidswinkels** [comment]
The description of Python commands has been improved, code blocks have been decreased and code was simplified to make it more readable.
